fix(Wrangler): F**k since Wrangler need more config key
$ wrangler publish
Error: You must specify either `workers_dev` or `route` and `zone_id` in order to publish.
The command "wrangler publish" exited with 1.